<?php 

class ContactsTableSeeder extends BaseTableSeeder {

    public function run() {
        $contacts = array(
            [
                'id' => 1,
                'consolidated_code' => '#11111111',
                'ten_digits_code' => '1111111111',
                'honorific' => 'Mr.',
                'firstname' => 'Mick',
                'lastname' => 'Jagger',
                'company' => 'Rolling Stones S.A.',
                'phone' => '5555-1111',
                'skype' => 'mick.jagger',
                'email' => 'mick@rollingstones.com',
                'position' => '',
                'id_market' => 4,
                'street' => '321 Abbey Road',
                'city' => 'Knebworth, London',
                'id_country' => 192,
                'postal_code' => '14280',
                'language' => 'English',
                'id_contact_type' => 1,
                'id_group_area' => 1,
                'career' => 'singer, vocals',
                'linkedin_profile' => 'https://ar.linkedin.com/in/mick-jagger-40446313',
            ],
            [
                'id' => 2,
                'consolidated_code' => '#22222222',
                'honorific' => 'Mr.',
                'firstname' => 'Keith',
                'lastname' => 'Richards',
                'company' => 'Rolling Stones S.A.',
                'phone' => '5555-2222',
                'skype' => 'keith.richards',
                'email' => 'keith@rollingstones.com',
                'position' => 'Lead guitar',
                'id_market' => 4,
                'street' => '321 Abbey Road',
                'city' => 'Knebworth, London',
                'id_country' => 192,
                'postal_code' => '14280',
                'language' => 'English',
                'id_contact_type' => 2,
                'id_group_area' => 1,
                'career' => 'guitar and melodiy',
                'linkedin_profile' => '',
            ],
            [
                'id' => 3,
                'consolidated_code' => '#33333333',
                'honorific' => 'Mr.',
                'firstname' => 'Charlie',
                'lastname' => 'Watts',
                'company' => 'Rolling Stones S.A.',
                'phone' => '5555-3333',
                'skype' => 'charlie.watts',
                'email' => 'charlie@rollingstones.com',
                'position' => 'Drums',
                'id_market' => 4,
                'street' => '321 Abbey Road',
                'city' => 'Knebworth, London',
                'id_country' => 192,
                'postal_code' => '14280',
                'language' => 'English',
                'id_contact_type' => 3,
                'id_group_area' => 1,
                'career' => 'rithm',
                'linkedin_profile' => '',
            ],
            [
                'id' => 4,
                'consolidated_code' => '#44444444',
                'honorific' => 'Mr.',
                'firstname' => 'Ron',
                'lastname' => 'Wood',
                'company' => 'Rolling Stones S.A.',
                'phone' => '5555-4444',
                'skype' => 'ron.wood',
                'email' => 'ron@rollingstones.com',
                'position' => 'Second guitar',
                'id_market' => 4,
                'street' => '321 Abbey Road',
                'city' => 'Knebworth, London',
                'id_country' => 192,
                'postal_code' => '14280',
                'language' => 'English',
                'id_contact_type' => 4,
                'id_group_area' => 1,
                'career' => 'melodic guitar',
                'linkedin_profile' => '',
            ]
        );
            
        $this->loadData('contacts', $contacts, 'App\Contact');
    }


}
